name: material_ui
description: My personalized Flutter theme package.
version: 1.0.0

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/assets/styles/silver_map_style.txt

  fonts:
    - family: Manrope
      fonts:
      - asset: lib/fonts/Manrope-Regular.ttf
        weight: 400
      - asset: lib/fonts/Manrope-Medium.ttf
        weight: 500
      - asset: lib/fonts/Manrope-Bold.ttf
        weight: 700
