import 'package:flutter/material.dart';

import 'package:material_ui/mat3_ui.dart';

/// These Material 3 colors generated by Material theme builder at:
/// https://m3.material.io/theme-builder#/custom
/// Verified by Lea.
ColorScheme lightColorScheme = ColorScheme.fromSeed(
    seedColor: Mat3Colors.lavenderWeb,
)
;
// ColorScheme lightColorScheme = ColorScheme(
//   brightness: Brightness.light,
//   primary: Mat3Colors.spaceCadet, //List tile selected
//   onPrimary: Mat3Colors.lavenderWeb[90]!,
//   primaryContainer:  Mat3Colors.primary[99],
//   onPrimaryContainer:Mat3Colors.primary,
//   secondary: Mat3Colors.secondary[95]!,
//   onSecondary: Mat3Colors.secondary,
//   secondaryContainer: Mat3Colors.lavenderWeb[95],
//   onSecondaryContainer: Mat3Colors.lavenderWeb[20],
//   tertiary: Mat3Colors.pumpkin,
//   onTertiary: Mat3Colors.mistyRose[50],
//   tertiaryContainer:Mat3Colors.bgLightMode,
//   onTertiaryContainer:  Mat3Colors.mistyRose[30],
//   error: Mat3Colors.error[20]!,
//   errorContainer: Mat3Colors.error,
//   onError: Mat3Colors.error[90]!,
//   onErrorContainer: Mat3Colors.error[95],
//   background: Mat3Colors.primary[80]!,
//   onBackground: Mat3Colors.primary[20]!,
//   surface: Color(0xFFFAFAFA),
//   onSurface: Color(0xFF2B2B2B),
//   surfaceVariant: Color(0xFFE3E3E3),
//   onSurfaceVariant: Color(0xFF494949),
//   outline: Color(0xFFE3E3E3),
//   onInverseSurface: Color(0xFFBFD5ED),
//   inverseSurface: Color(0xFF001A37),
//   inversePrimary: Mat3Colors.platinum[90],
//   shadow: Mat3Colors.primary[30],
//   surfaceTint: Mat3Colors.mistyRose[80],
//   // outlineVariant: Color(0xFFC4C6D0),
//   // scrim: Color(0xFF000000),
// );

/// These Material 3 colors generated by Material theme builder at:
/// https://m3.material.io/theme-builder#/custom
/// Verified by Lea.
  ColorScheme darkColorScheme = ColorScheme.fromSeed(
seedColor: Mat3Colors.primary,
      brightness: Brightness.dark,
  // brightness: Brightness.dark,
  // primary: Mat3Colors.lavenderWeb[90]!, //List tile selected
  // onPrimary: Mat3Colors.spaceCadet,
  // primaryContainer: Mat3Colors.primary,
  // onPrimaryContainer: Mat3Colors.primary[99],
  // secondary: Mat3Colors.secondary,
  // onSecondary: Mat3Colors.secondary[95]!,
  // secondaryContainer: Mat3Colors.lavenderWeb[20],
  // onSecondaryContainer: Mat3Colors.lavenderWeb[95],
  //   tertiary: Mat3Colors.mistyRose[50],
  //   onTertiary: Mat3Colors.pumpkin,
  //   tertiaryContainer: Mat3Colors.mistyRose[30],
  // onTertiaryContainer: Mat3Colors.bgLightMode,
  // error: Mat3Colors.error,
  // errorContainer: Mat3Colors.error[20],
  // onError: Mat3Colors.error[95]!,
  // onErrorContainer: Mat3Colors.error[90],
  // background: Mat3Colors.primary[20]!,
  // onBackground: Mat3Colors.primary[80]!,
  // surface: Color(0xFF2B2B2B),
  // onSurface: Color(0xFFC8C8C8),
  // surfaceVariant: Color(0xFF232323),
  // onSurfaceVariant: Color(0xFF333333),
  // outline: Color(0xFF2C2C2C),
  // onInverseSurface: Color(0xFF001A37),
  // inverseSurface: Color(0xFFBFD5ED),
  // inversePrimary: Mat3Colors.platinum[30],
  // shadow: Mat3Colors.platinum[80],
  // surfaceTint: Mat3Colors.lavenderWeb[80],
  // // outlineVariant: Color(0xFF44474F),
  // // scrim: Color(0xFF000000),
);
